import day07.{parse_input, part1, part2}
import gleam/string
import gleeunit

pub fn main() -> Nil {
  gleeunit.main()
}

const input_str = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

// gleeunit test functions end in `_test`
pub fn part1_test() {
  let lines =
    input_str
    |> string.split("\n")

  let #(start, splitters) = parse_input(lines)
  assert part1(start, splitters) == 21
}

pub fn part2_test() {
  let lines =
    input_str
    |> string.split("\n")
  let #(start, splitters) = parse_input(lines)
  assert part2(start, splitters) == 40
}
